# API 项目标签配置
# 格式: 标签名: 文件路径匹配规则

# API 控制器变更
controllers:
- src/**/controllers/**/*
- src/**/*.controller.ts

# 服务层变更
services:
- src/**/services/**/*
- src/**/*.service.ts

# 数据模型变更
models:
- src/**/models/**/*
- src/**/dto/**/*
- src/**/entities/**/*
- src/**/*.model.ts
- src/**/*.entity.ts
- src/**/*.dto.ts

# 中间件变更
middleware:
- src/**/middleware/**/*
- src/**/*.middleware.ts
- src/**/*.interceptor.ts
- src/**/*.filter.ts
- src/**/*.guard.ts

# 测试相关变更
test:
- '**/*.test.ts'
- '**/*.spec.ts'
- src/**/__tests__/**/*
- test/**/*

# 配置文件变更
configuration:
- src/**/config/**/*
- '**/*.yml'
- '**/*.yaml'
- '**/*.json'
- '**/*.config.ts'
- '**/*.config.js'

# CI/CD 相关变更
ci:
- .github/workflows/**/*