name: PR Agent (Gemini)
on:
    pull_request:
        types: [opened, reopened, ready_for_review]
    issue_comment:
        permissions:
            contents: read
jobs:
    pr_agent_job:
        if: github.event.sender.type != 'Bot' ||
            !contains(github.event.sender.login, 'bot') ||
            !contains(github.event.sender.login, '[bot]') ||
            !contains(github.event.sender.login, '(Bot)') ||
            github.event.workflow_run.head_commit.author.login != github.event.sender.login ||
            !contains(github.event.workflow_run.head_commit.author.login, 'bot') ||
            !contains(github.event.workflow_run.head_commit.author.login, '[bot]') ||
            !contains(github.event.workflow_run.head_commit.author.login, '(Bot)') ||
            (github.event_name != 'pull_request' || (
            github.event.pull_request.user.login != github.event.sender.login ||
            !contains(github.event.pull_request.user.login, 'bot') ||
            !contains(github.event.pull_request.user.login, '[bot]') ||
            !contains(github.event.pull_request.user.login, '(Bot)')))
        runs-on: ubuntu-latest
        permissions:
            issues: write
            pull-requests: write
            contents: write
        steps:
            - name: Harden the runner (Audit all outbound calls)
              uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
              with:
                  egress-policy: audit
            - name: PR Agent action step
              uses: qodo-ai/pr-agent@d36ad319f7fb0049205017405a71275c41599587 # main
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  config.model: "gemini/gemini-1.5-flash"
                  config.fallback_models: '["gemini/gemini-1.5-flash"]'
                  GOOGLE_AI_STUDIO.GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
                  github_action_config.auto_review: "true"
                  github_action_config.auto_describe: "true"
                  github_action_config.auto_improve: "true"
